# Generated by Django 3.0.10 on 2020-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
    ]
