# Generated by Django 3.0.10 on 2020-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheraudit',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weatheraudit',
            name='description',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weatheraudit',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='weatheraudit',
            name='temperature',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
